variables:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 058264373862.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY: generic/repo
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

stages:
  - build

build_release:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - apk add --no-cache aws-cli
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
  script:
    - cd modules/fastapi-poc/src
    - docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
    - docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
    - docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    - docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
    - |
      echo "Image pushed successfully:"
      echo "- $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
      echo "- $ECR_REGISTRY/$ECR_REPOSITORY:latest"
  only:
    - main
    - merge_requests
